namespace Atlassian.Jira.OAuth
{
    /// <summary>
    /// Request token information returned by Jira.
    /// </summary>
    public class OAuthRequestToken
    {
        public readonly string AuthorizeUri;
        public readonly string OAuthToken;
        public readonly string OAuthTokenSecret;
        public readonly string OAuthCallbackConfirmation;

        /// <summary>
        /// Creates a request token containing the response from Jira.
        /// </summary>
        /// <param name="authorizeUri">The url to authorize the request token generated by Jira.</param>
        /// <param name="oAuthToken">The OAuth request token generated by Jira.</param>
        /// <param name="oAuthTokenSecret">The OAuth token secret generated by Jira.</param>
        public OAuthRequestToken(string authorizeUri, string oAuthToken, string oAuthTokenSecret, string oauthCallbackConfirmation)
        {
            AuthorizeUri = authorizeUri;
            OAuthToken = oAuthToken;
            OAuthTokenSecret = oAuthTokenSecret;
            OAuthCallbackConfirmation = oauthCallbackConfirmation;
        }
    }
}
